apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "packetai-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "packetai-agent.fullname" . }}
  namespace: {{ template "packetai-agent.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "packetai-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
