---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "packetai-agent.fullname" . }}-cluster-agent-configmap
  namespace: {{ template "packetai-agent.namespace" . }}
  labels:
    k8s-app: {{ template "packetai-agent.fullname" . }}
data:
  global-metric-config.yml: |
{{ .Values.clusterAgent.metricConfig | toYaml | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "packetai-agent.fullname" . }}-node-agent-configmap
  namespace: {{ template "packetai-agent.namespace" . }}
  labels:
    k8s-app: {{ template "packetai-agent.fullname" . }}
data:
  global-log-config.yml: |
{{ .Values.nodeAgent.logConfig | toYaml | indent 4 }}
  global-metric-config.yml: |
{{ .Values.nodeAgent.metricConfig | toYaml | indent 4 }}
