apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "packetai-agent.fullname" . }}-cluster
  namespace: {{ template "packetai-agent.namespace" . }}
  labels:
    k8s-app: {{ template "packetai-agent.fullname" . }}-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ template "packetai-agent.fullname" . }}-cluster
  template:
    metadata:
      labels:
        k8s-app: {{ template "packetai-agent.fullname" . }}-cluster
    spec:
      serviceAccountName: {{ template "packetai-agent.fullname" . }}
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pai-cluster-topo
        image: "{{ .Values.clusterAgent.topo.image.repository }}:{{ .Values.global.imageTag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.clusterAgent.topo.image.pullPolicy }}
        env:
        {{- if .Values.global.kubeStateMetrics.enabled }}
        - name: KUBERNETES_STATE_METRICS_ENDPOINT
          value: {{ (printf "%s-kube-state-metrics:8080" (.Release.Name)) }}
        {{- else }}  
        - name: KUBERNETES_STATE_METRICS_ENDPOINT
          value: {{ required "global.kubeStateMetrics.url is compulsory to collect metrics" .Values.global.kubeStateMetrics.url }}
        {{- end }}
        - name: KUBERNETES_PROXY_ENDPOINT
          value: {{ .Values.global.k8sProxyEndPoint }}
        - name: APIDEVURL
          value: {{ required "global.apiUrl is compulsory" .Values.global.apiUrl }}
        - name: X_PAI_TOKEN
          value: {{ required "global.xPaiToken is compulsory" .Values.global.xPaiToken }}
        - name: PAI_API_KEY
          value: {{ required "global.paiApiKey is compulsory" .Values.global.paiApiKey }}
        - name: CLUSTER_NAME
          value:  {{ required "global.clusterName is compulsory" .Values.global.clusterName }}
        - name: BLACK_LIST_CONTAINERS_NAME_PATTERN
          value:  {{ .Values.global.blacklistContainers }}
        - name: WHITE_LIST_NAMESPACES
          value:  {{ .Values.global.whitelistNamespaces }}
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
            {{- toYaml .Values.clusterAgent.topo.resources | nindent 10 }}
      - name: pai-cluster-agent
        image: "{{ .Values.clusterAgent.metrics.image.repository }}:{{ .Values.global.imageTag | default .Chart.AppVersion }}"
        args: ["-level", "cluster"]
        imagePullPolicy: {{ .Values.clusterAgent.metrics.image.pullPolicy }}
        env:
        {{- if .Values.global.kubeStateMetrics.enabled }}
        - name: KUBERNETES_STATE_METRICS_ENDPOINT
          value: {{ (printf "%s-kube-state-metrics:8080" (.Release.Name)) }}
        {{- else }}  
        - name: KUBERNETES_STATE_METRICS_ENDPOINT
          value: {{ required "global.kubeStateMetrics.url is compulsory to collect metrics" .Values.global.kubeStateMetrics.url }}
        {{- end }}
        - name: KUBERNETES_PROXY_ENDPOINT
          value: {{ .Values.global.k8sProxyEndPoint }}
        - name: APIDEVURL
          value: {{ required "global.apiUrl is compulsory" .Values.global.apiUrl }}
        - name: X_PAI_TOKEN
          value: {{ required "global.xPaiToken is compulsory" .Values.global.xPaiToken }}
        - name: PAI_API_KEY
          value: {{ required "global.paiApiKey is compulsory" .Values.global.paiApiKey }}
        - name: CLUSTER_NAME
          value:  {{ required "global.clusterName is compulsory" .Values.global.clusterName }}
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
            {{- toYaml .Values.clusterAgent.metrics.resources | nindent 10 }}
      {{- with .Values.clusterAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clusterAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clusterAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}