apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "packetai-agent.fullname" . }}-agent
  labels:
    k8s-app: {{ include "packetai-agent.fullname" . }}-agent
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
