apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "packetai-agent.fullname" . }}
  namespace: {{ template "packetai-agent.namespace" . }}
  labels:
    k8s-app: {{ template "packetai-agent.fullname" . }}
